### ISSUE TITLE
TO DO List

### ISSUE THREAD

**Issue by bigtreetech** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1830]
### Bugfix
 - [x] Klipper 12864 mode #290 
**progress:** The API Application of the upper layer is basically implemented in #705 . In my test, the problem occurs in the SPI slave part of the bottom layer. The SPI data received from klipper will shift by one bit. 
 - [x] RGB Printing heating color not change #1786
**progress:** In fact, it is not a really bug, It's a known limitation. Marlin will activate the LED change only after receiving the "M190/M109" gcode, but this gcode will cause the communication interruption between the TFT and Marlin (because Marlin will not respond to other gcode before reaching the target temperature), so TFT will convert this gcode to "M140/M104" to avoid communication interruption, but Marlin will not be able to activate the LED change normally.

### Improve
 - [x] Restructure `platformio.ini` File, using the relying on expansion to avoid redundancy
 - [ ] Restructure `icon/list`/etc... menu API (and related touch API) provides a more general API interface
 - [x] Neopixel header LED number #1764
 - [x] Machine RGB setting custom color value #1687

### Development direction
 - [x] Vertical Screen #524
 - [ ] CNC Menu #1750

**Comment by oldman4U** [comment]
I would add "Developers wanted" to the headline.

**Comment by digant73** [comment]
I can implement the machine RGB settings custom color.
My idea is to to provide in the current RGB menu:
1) a standard color select button. A list menu reporting standard colors will be used to select the color
2) a custom color select button. A new menu to select the RGB components will be available to set color. The menu will be usable as general RGB color pickup. A proper callback to handle the selected color will be registered. E.g. a callback to set the printer LED color etc...
3) a button to switch between standard/custom selected color
4) a ON/OFF button to switch on/of the printer LED

**Comment by digant73** [comment]
could it OK as menu to select a custom LED RGB color?
I will add also the W, intensity and index for NEO Pixel

![IMG_20210415_231203](https://user-images.githubusercontent.com/64427768/115012745-7b992980-9eb0-11eb-80a1-614d9682d69e.jpg)

**Comment by oldman4U** [comment]
Can you click on the value to get a keypad?
Can you see the resulting colour somewhere (approximately;-))?

**Comment by digant73** [comment]
yes for both questions

**Comment by sinole1987** [comment]
can you add mid print nozzle freezing to the to do list. Its a very big issue and never got fixed. last night I had another freez. It mostly happen on long prints.

**Comment by digant73** [comment]
wasn't "Restructure icon/list/etc... menu API (and related touch API) provides a more general API interface" recently implemented by Gurmeet with his last merged PR?

**Comment by guruathwal** [comment]
> wasn't "Restructure icon/list/etc... menu API (and related touch API) provides a more general API interface" recently implemented by Gurmeet with his last merged PR?

not completely, I am still working on it.

**Comment by bttguy** [comment]
@bigtreetech Can I ask you to include some RRF related improvements listed in #1791? I can help you with testing :)

**Comment by bigtreetech** [comment]
> @bigtreetech Can I ask you to include some RRF related improvements listed in #1791? I can help you with testing :)

Hello, It is being implemented in #1962

**Comment by guruathwal** [comment]
Dear Stale bot, please don't mark this one as stale. 😂

**Comment by Minims** [comment]
Hello, is it possible to add a moonraker api compatibilty layer to use the TOuchscreen mode on klipper, like paneldue or the ender3v2 screen ? Thx!

**Comment by sarvenn** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

@oldman4U . Topic is about to be closed.

**Comment by oldman4U** [comment]
Hi sarvenn.

I am not the owner but such tickets are automatically reopened.

**Comment by sarvenn** [comment]
> Hi sarvenn.
> 
> I am not the owner but such tickets are automatically reopened.

Oh, sorry. :) I missed that. You are the first one came up in my mind for this platform 😃

@bigtreetech for your information.

**Comment by yannick-alch** [comment]
> can you add mid print nozzle freezing to the to do list. Its a very big issue and never got fixed. last night I had another freez. It mostly happen on long prints.

I have the same problem on long print. The nozzle freeze into the piece, and motor are still lock and temperature are kept. Maybe the screen didn't received the "ok" response from the motherboard ?
Is there a way to resent the "ok" message after an amount of time ?

**Comment by digant73** [comment]
@bigtreetech Event LED feature could be now marked as done. Also PR #1209 could be removed. All the features on that PR have been implemented.

**Comment by sinole1987** [comment]
> > can you add mid print nozzle freezing to the to do list. Its a very big issue and never got fixed. last night I had another freez. It mostly happen on long prints.
> 
> @sinole1987 I have the same problem on long print. The nozzle freeze into the piece, and motor are still lock and temperature are kept. Maybe the screen didn't received the "ok" response from the motherboard ? Is there a way to resent the "ok" message after an amount of time ?

you need to make a sleeved cable out of a usb cable and use the braded jacket for ground pin and 24 awg red cable for power. after that you need to wrap it in ferrite beads on both ends. It will get much better.

**Comment by digant73** [comment]
please stay with us

**Comment by sinole1987** [comment]
Not the todo list :)

**Comment by thisiskeithb** [comment]
@bigtreetech You need to add the `TODO` label to this issue so stalebot doesn't close this.

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/1e5955e76d764e830ca707508052275d31f2e95e/.github/stale.yml#L13-L18

**Comment by Tannoo** [comment]
You mean "TO DO"? Or the title needs to be changed to "TODO".

**Comment by oldman4U** [comment]
ToDo ;-)

**Comment by xPew** [comment]
Just some more time dear bot!

**Comment by oldman4U** [comment]
MAGIC!!!😁

**Comment by guruathwal** [comment]
Mr Stale is the only person regularly maintaining this repo 🤣

**Comment by oldman4U** [comment]
And me. 😁
